/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookmarksRouteImport } from './routes/bookmarks'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SurahIndexRouteImport } from './routes/$surah/index'
import { Route as SurahPageIndexRouteImport } from './routes/$surah/$page/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksRoute = BookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SurahIndexRoute = SurahIndexRouteImport.update({
  id: '/$surah/',
  path: '/$surah/',
  getParentRoute: () => rootRouteImport,
} as any)
const SurahPageIndexRoute = SurahPageIndexRouteImport.update({
  id: '/$surah/$page/',
  path: '/$surah/$page/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bookmarks': typeof BookmarksRoute
  '/settings': typeof SettingsRoute
  '/$surah/': typeof SurahIndexRoute
  '/$surah/$page/': typeof SurahPageIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bookmarks': typeof BookmarksRoute
  '/settings': typeof SettingsRoute
  '/$surah': typeof SurahIndexRoute
  '/$surah/$page': typeof SurahPageIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bookmarks': typeof BookmarksRoute
  '/settings': typeof SettingsRoute
  '/$surah/': typeof SurahIndexRoute
  '/$surah/$page/': typeof SurahPageIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bookmarks' | '/settings' | '/$surah/' | '/$surah/$page/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bookmarks' | '/settings' | '/$surah' | '/$surah/$page'
  id:
    | '__root__'
    | '/'
    | '/bookmarks'
    | '/settings'
    | '/$surah/'
    | '/$surah/$page/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookmarksRoute: typeof BookmarksRoute
  SettingsRoute: typeof SettingsRoute
  SurahIndexRoute: typeof SurahIndexRoute
  SurahPageIndexRoute: typeof SurahPageIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks': {
      id: '/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof BookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$surah/': {
      id: '/$surah/'
      path: '/$surah'
      fullPath: '/$surah/'
      preLoaderRoute: typeof SurahIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$surah/$page/': {
      id: '/$surah/$page/'
      path: '/$surah/$page'
      fullPath: '/$surah/$page/'
      preLoaderRoute: typeof SurahPageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookmarksRoute: BookmarksRoute,
  SettingsRoute: SettingsRoute,
  SurahIndexRoute: SurahIndexRoute,
  SurahPageIndexRoute: SurahPageIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
