/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SurahSlugRouteImport } from './routes/$surahSlug'
import { Route as AboutRouteImport } from './routes/about'
import { Route as SurahSlugPagePageNumberRouteImport } from './routes/$surahSlug.page.$pageNumber'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SurahSlugRoute = SurahSlugRouteImport.update({
  id: '/$surahSlug',
  path: '/$surahSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const SurahSlugPagePageNumberRoute = SurahSlugPagePageNumberRouteImport.update({
  id: '/page/$pageNumber',
  path: '/page/$pageNumber',
  getParentRoute: () => SurahSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$surahSlug': typeof SurahSlugRouteWithChildren
  '/about': typeof AboutRoute
  '/$surahSlug/page/$pageNumber': typeof SurahSlugPagePageNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$surahSlug': typeof SurahSlugRouteWithChildren
  '/about': typeof AboutRoute
  '/$surahSlug/page/$pageNumber': typeof SurahSlugPagePageNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$surahSlug': typeof SurahSlugRouteWithChildren
  '/about': typeof AboutRoute
  '/$surahSlug/page/$pageNumber': typeof SurahSlugPagePageNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$surahSlug' | '/about' | '/$surahSlug/page/$pageNumber'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$surahSlug' | '/about' | '/$surahSlug/page/$pageNumber'
  id:
    '__root__' | '/' | '/$surahSlug' | '/about' | '/$surahSlug/page/$pageNumber'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SurahSlugRoute: typeof SurahSlugRouteWithChildren
  AboutRoute: typeof AboutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$surahSlug': {
      id: '/$surahSlug'
      path: '/$surahSlug'
      fullPath: '/$surahSlug'
      preLoaderRoute: typeof SurahSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$surahSlug/page/$pageNumber': {
      id: '/$surahSlug/page/$pageNumber'
      path: '/page/$pageNumber'
      fullPath: '/$surahSlug/page/$pageNumber'
      preLoaderRoute: typeof SurahSlugPagePageNumberRouteImport
      parentRoute: typeof SurahSlugRoute
    }
  }
}

interface SurahSlugRouteChildren {
  SurahSlugPagePageNumberRoute: typeof SurahSlugPagePageNumberRoute
}

const SurahSlugRouteChildren: SurahSlugRouteChildren = {
  SurahSlugPagePageNumberRoute: SurahSlugPagePageNumberRoute,
}

const SurahSlugRouteWithChildren = SurahSlugRoute._addFileChildren(
  SurahSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SurahSlugRoute: SurahSlugRouteWithChildren,
  AboutRoute: AboutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
